<?php
/**
 * @file
 * Code for the country_data feature.
 */

include_once 'country_data.features.inc';

/**
 * Registers the countries path and includes a page callback.
 *
 * @return
 *   An associative array of properties for each path.
 */
function country_data_menu() {
  $items['countries'] = array(
    'title' => 'Countries',
    'page callback' => 'country_data_page_callback',
    'access arguments' => array('access content')
  );

  return $items;
}

/**
 * Displays the countries page when the user visits the path.
 *
 * @return
 *   String representing the content of the page.
 */
function country_data_page_callback() {
  // Adds the amCharts JavaScript files to the page.
  drupal_add_js('http://www.amcharts.com/lib/3/ammap.js', 'external');
  drupal_add_js('http://www.amcharts.com/lib/3/maps/js/worldHigh.js', 'external');
  drupal_add_js('http://www.amcharts.com/lib/3/themes/light.js', 'external');

  // Adds the countries JavaScript file to the page.
  drupal_add_js(drupal_get_path('module', 'country_data') . '/js/countries.js');

  return theme('countries');
}

/**
 * Registers module's theme implementations.
 *
 * @return
 *   An associative array of theme hook information.
 */
function country_data_theme() {
  return array(
    'countries' => array()
  );
}
