<?php
/**
 * @file
 * Code for the country_data feature.
 */

include_once 'country_data.features.inc';

function country_data_theme() {
	return array(
		'country_data_contact_person' => array(
			'render element' => 'element',
			'template' => 'templates/country-data-contact-person',
			'variables' => array('contact_person' => NULL, 'treaty' => NULL),
			'path' => drupal_get_path('module', 'country_data'),
		),
	);
}