<?php
/**
 * @file
 * Code for the country_data feature.
 */

include_once 'country_data.features.inc';

/**
 * Defines menu items and page callbacks.
 *
 * @return
 *   An associative array of properties for each path.
 */
function country_data_menu() {
  $items['countries'] = array(
    'title' => t('Countries'),
    'page callback' => 'country_data_map_view',
    'access arguments' => array('access content')
  );

  $items['countries/list'] = array(
    'title' => 'Countries',
    'page callback' => 'country_data_list_view',
    'access arguments' => array('access content')
  );

  return $items;
}

/**
 * Registers module's theme implementations.
 *
 * @return
 *   An associative array of theme hook information.
 */
function country_data_theme() {
  return array(
    'countries_list' => array(
      'variables' => array(
        'index' => NULL
      )
    ),
    'countries_map' => array()
  );
}

/**
 * Loads the properties of areas.
 *
 * @return
 *   An associative array of properties for each area.
 */
function _country_data_get_areas() {
  // Loads all properties of enabled countries.
  $countries = countries_get_countries('all', array('enabled' => COUNTRIES_ENABLED));

  foreach ($countries as $iso2 => $country) {
    $areas[] = array('id' => $iso2);
  }

  return $areas;
}

/**
 * Displays the countries map page when the user visits the path.
 *
 * @return
 *   String representing the content of the page.
 */
function country_data_map_view() {
  // Adds the amCharts JavaScript files to the page.
  drupal_add_js('http://www.amcharts.com/lib/3/ammap.js', 'external');
  drupal_add_js('http://www.amcharts.com/lib/3/maps/js/worldHigh.js', 'external');
  drupal_add_js('http://www.amcharts.com/lib/3/themes/light.js', 'external');

  // Adds the properties of areas to Drupal's global storage of JavaScript
  // settings.
  drupal_add_js(array('areas' => _country_data_get_areas()), 'setting');

  // Adds the countries map JavaScript file to the page.
  drupal_add_js(drupal_get_path('module', 'country_data') . '/js/countries-map.js');

  return theme('countries_map');
}

/**
 * Loads the alphabetical index of countries.
 *
 * @return
 *   An associative array of countries indexed by first letter.
 */
function _country_data_get_index() {
  $index = array();

  // Loads the names of enabled countries.
  $countries = countries_get_countries('name', array('enabled' => COUNTRIES_ENABLED));

  foreach ($countries as $iso2 => $name) {
    $index[mb_substr($name, 0, 1)][$iso2] = $name;
  }

  return $index;
}

/**
 * Displays the countries list page when the user visits the path.
 *
 * @return
 *   String representing the content of the page.
 */
function country_data_list_view() {
  // Adds the countries list JavaScript file to the page.
  drupal_add_js(drupal_get_path('module', 'country_data') . '/js/countries-list.js');

  return theme('countries_list', array('index' => _country_data_get_index()));
}

/**
 * Preprocesses variables for page template.
 *
 * @param $variables
 *   An associative array with generated variables.
 *
 * @return
 *   Nothing.
 */
function country_data_preprocess_page(&$variables) {
  switch (current_path()) {
    case 'countries':
      $variables['theme_hook_suggestions'][] = 'page__countries_map';

      break;

    case 'countries/list':
      $variables['theme_hook_suggestions'][] = 'page__countries_list';

      break;
  }
}
