<?php

define('EDW_AMCHARTS_VERSION', '0.1');

/**
 *  Implements hook_menu().
 */
function edw_amcharts_menu() {
  $items['amcharts/ajax/%/%'] = array(
    'title' => t('Ajax endpoint for amcharts plugin'),
    'page callback' => 'edw_amcharts_ajax_process',
    'access callback' => 'edw_amcharts_ajax_access',
    'access arguments' => array(2, 3),
  );
  return $items;
}

/**
 * Check access to the Ajax endpoint.
 *
 * @return bool
 *   TRUE if access is granted
 */
function edw_amcharts_ajax_access($arg0, $arg1) {
  $ret = TRUE;
  drupal_alter('edw_amcharts_ajax_access', $ret);
  return $ret;
}


/**
 *  Implements hook_library().
 */
function edw_amcharts_library() {
  $base_js = array(
    'http://cdn.amcharts.com/lib/3/amcharts.js' => array(
      'type' => 'external',
      'group' => JS_LIBRARY,
      'weight' => 10,
    ),
  );

  $items['edw_amcharts_library'] = array(
    'title' => 'amCharts library',
    'version' => EDW_AMCHARTS_VERSION,
    'js' => $base_js,
  );

  $items['edw_amcharts_column_chart'] = array(
    'title' => 'amCharts column chart',
    'version' => EDW_AMCHARTS_VERSION,
    'js' => $base_js + array(
        'http://www.amcharts.com/lib/3/serial.js' => array(
          'type' => 'external',
          'group' => JS_LIBRARY,
          'weight' => 20,
        ),
      )
  );

  $items['edw_amcharts_pie_chart'] = array(
    'title' => 'amCharts pie chart',
    'version' => EDW_AMCHARTS_VERSION,
    'js' => $base_js + array(
        'http://www.amcharts.com/lib/3/pie.js' => array(
          'type' => 'external',
          'group' => JS_LIBRARY,
          'weight' => 20,
        ),
      ),
  );
  return $items;
}

/**
 * Add components needed to generate a chart.
 *
 * @param string $chart_id
 *  Unique chart id (assigned to the enclosing <div>)
 * @param string $chart_type
 *  Type of chart (see amCharts documentation)
 * @param object $chart_config
 *  The actual chart data (Array of objects which will be serialized to JSON)
 * @param array $options
 *  Extra options (theme, width, height) passed to the amCharts library.
 */
function edw_amcharts_add_chart($chart_id, $chart_type, $chart_config, $options = array()) {
  $defaults = $options + array(
      'width' => '100px',
      'height' => '100px',
  );
  drupal_alter('edw_amcharts_chart_data', $chart_config, $chart_id);
  drupal_add_library('edw_amcharts', "edw_amcharts_{$chart_type}_chart");
  drupal_add_js("http://www.amcharts.com/lib/3/themes/{$chart_config->theme}.js",
    array(
      'type' => 'external', 'group' => JS_LIBRARY, 'weight' => 30,
    )
  );
  $config = json_encode($chart_config, JSON_PRETTY_PRINT);
  $js_config = <<<EOF
jQuery(document).ready(function ($) {
  var chart = AmCharts.makeChart("$chart_id", {$config});

  // Legislation
  chart.addListener('clickSlice', function (event) {
    var params = {
      f: [
        'field_country:' + event.dataItem.dataContext.nid,
        'type:legislation',
        'field_type_of_text:' + event.dataItem.dataContext.tid
      ],
      search_api_views_fulltext_op: 'AND'
    };

    window.location.href = Drupal.settings.basePath + 'search?' + $.param(params);
  });

  // Literature
  chart.addListener('clickGraphItem', function (event) {
    var params = {
      f: [
        'field_country:' + event.item.dataContext.nid,
        'type:literature',
        'field_literature_type:' + event.item.dataContext.tid
      ],
      search_api_views_fulltext_op: 'AND'
    };

    window.location.href = Drupal.settings.basePath + 'search?' + $.param(params);
  });
});
EOF;

  $width = $defaults['width'];
  $height = $defaults['height'];
  drupal_add_js($js_config, 'inline');
  $css = <<<EOF
    #$chart_id { width: $width; height: $height; }
EOF;

  drupal_add_css($css, 'inline');
}

/**
 * Ajax endpoint processor.
 */
function edw_amcharts_ajax_process() {
  echo '[]';
  drupal_exit();
}


function edw_amcharts_default_config_chart_column() {
  return (object)array(
    'type' => 'serial',
    'theme' => 'none',
    'valueAxes' => array( (object) array(
      'gridColor' =>'#FFFFFF',
      'gridAlpha' => 0.2,
      'dashLength' => 0
    )),
    'gridAboveGraphs' => true,
    'startDuration' => 1,
    'graphs' => array( (object) array(
      'balloonText' => '[[category]] => <b>[[value]]</b>',
      'fillAlphas' => 0.8,
      'lineAlpha' => 0.2,
      'type' => 'column',
      'valueField' => 'the_value'
    )),
    'chartCursor' => (object) array(
      'categoryBalloonEnabled' => FALSE,
        'cursorAlpha' => 0,
        'zoomable' => FALSE
    ),
    'categoryField' => 'the_category',
    'categoryAxis' => (object) array(
    'gridPosition' => 'start',
        'gridAlpha' => 0,
         'tickPosition' =>'start',
         'tickLength' => 20
    ),
    'dataProvider' => array(
      (object) array('the_category' => 'USA', 'the_value' => 2025),
      (object) array('the_category' => 'China', 'the_value' => 1882),
      (object) array('the_category' => 'Japan', 'the_value' => 1809),
      (object) array('the_category' => 'Germany', 'the_value' => 1322)
    )
  );
}


function edw_amcharts_default_config_chart_pie() {
  return (object)array(
    'type' => 'pie',
    'theme' => 'none',
    'valueField' => 'the_value',
    'titleField' => 'the_title',
    'dataProvider' => array(
      (object) array('the_title' => 'USA', 'the_value' => 2025),
      (object) array('the_title' => 'China', 'the_value' => 1882),
      (object) array('the_title' => 'Japan', 'the_value' => 1809),
      (object) array('the_title' => 'Germany', 'the_value' => 1322)
    )
  );
}
