<?php
/**
 * @file
 * country_deliverable.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function country_deliverable_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_country'
  $field_bases['field_country'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_country',
    'foreign keys' => array(),
    'indexes' => array(
      'iso2' => array(
        0 => 'iso2',
      ),
    ),
    'locked' => 0,
    'module' => 'countries',
    'settings' => array(
      'continents' => array(),
      'countries' => array(),
      'enabled' => 1,
      'entity_translation_sync' => FALSE,
      'size' => 5,
    ),
    'translatable' => 0,
    'type' => 'country',
  );

  return $field_bases;
}
