<?php
/**
 * @file
 * Code for the search_integration feature.
 */

include_once 'search_integration.features.inc';

/**
 * Implements hook_form_alter().
 *
 * Fix the integration between facet filters and views exposed keyword search.
 *
 * {@inheritdoc}
 */
function search_integration_form_alter(&$form, &$form_state) {
  /**
   * SITUATION: Search forms with facet filters and keywords search.
   * PROBLEM: When searching for a keyword after using a facet filter, the
   * facet filter is ignored by Views.
   * SOLUTION: Add facet filters as hidden form fields to Views exposed forms.
   */

  // Check if this form is a Search API form. This could be replaced with the
  // value of a custom Views setting like ie. "Include facets".
  if (isset($form_state['view']) && $form_state['view']->base_field === 'search_api_id') {
    // Get quary parameters.
    $query_parameters = drupal_get_query_parameters();

    // If any facet query parameters are provided.
    if (!empty($query_parameters['f'])) {
      // Iterate through facet query parameters.
      foreach($query_parameters['f'] as $key => $value) {
        // Add hidden form field for facet parameter.
        $form['f[' . $key . ']'] = array(
          '#type' => 'hidden',
          '#value' => $value,
          '#weight' => -1,
        );
      }
    }
  }
}
