<?php
/**
 * @file
 * informea_search.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function informea_search_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-3KWtmCIzHfDw1AIpfhJ6xCbHm5eyrM1x'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '3KWtmCIzHfDw1AIpfhJ6xCbHm5eyrM1x',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'search-publications
search-publications/*',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -28,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Region',
    'visibility' => 1,
  );

  $export['facetapi-3mJm1W4dfmvVJwQU6Fwa1UYCADF630r5'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '3mJm1W4dfmvVJwQU6Fwa1UYCADF630r5',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'search-publications
search-publications/*',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -34,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Type',
    'visibility' => 1,
  );

  $export['facetapi-5dVDefUus1Cng13EbCDnPRh5v5tXEP7B'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '5dVDefUus1Cng13EbCDnPRh5v5tXEP7B',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'informea_theme',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-7R00LhqRFhlzPLK775MhkBao9G1ddsJq'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '7R00LhqRFhlzPLK775MhkBao9G1ddsJq',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -33,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Document type',
    'visibility' => 0,
  );

  $export['facetapi-ABol1qBh79jsfGqF27usDpaBznEzCn7M'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'ABol1qBh79jsfGqF27usDpaBznEzCn7M',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'search-court-decisions
search-court-decisions/*',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -41,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Type of text',
    'visibility' => 1,
  );

  $export['facetapi-C0KfOYe1CTJW1tlSyl3brJVVT4qQLzy0'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'C0KfOYe1CTJW1tlSyl3brJVVT4qQLzy0',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'search
search/*
search-bilateral-treaties
search-bilateral-treaties/*',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -47,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Instrument',
    'visibility' => 1,
  );

  $export['facetapi-EBe4nF0bWIclTeTpPk5EfoKyGT3EgxZw'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'EBe4nF0bWIclTeTpPk5EfoKyGT3EgxZw',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'search-legislation
search-legislation/*',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -39,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Region',
    'visibility' => 1,
  );

  $export['facetapi-EPopgYUIPRwLmsNXr9X8D1FoiB4vdkPG'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'EPopgYUIPRwLmsNXr9X8D1FoiB4vdkPG',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'search-publications
search-publications/*
documents',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -32,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Country',
    'visibility' => 1,
  );

  $export['facetapi-EeqfYRvf4OeayxrDPBXmxh0uLs695r1S'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'EeqfYRvf4OeayxrDPBXmxh0uLs695r1S',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'search
search/*
search-bilateral-treaties
search-bilateral-treaties/*',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -46,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Geographical region',
    'visibility' => 1,
  );

  $export['facetapi-I6RVf55CR0muKADP1zTBRoXexXDd7LN4'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'I6RVf55CR0muKADP1zTBRoXexXDd7LN4',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'search
search/*
search-bilateral-treaties
search-bilateral-treaties/*',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -44,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'LEO terms',
    'visibility' => 1,
  );

  $export['facetapi-IhbpziRRQ04ohXLVPOH1pzkj01ySLvut'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'IhbpziRRQ04ohXLVPOH1pzkj01ySLvut',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'search-legislation
search-legislation/*',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -40,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Country',
    'visibility' => 1,
  );

  $export['facetapi-IyeCKCprQMtwZlPzlV9rNi3D01lK0oqY'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'IyeCKCprQMtwZlPzlV9rNi3D01lK0oqY',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'search-publications
search-publications/*',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -31,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Geographical scope',
    'visibility' => 1,
  );

  $export['facetapi-O1SxmXX8M8WxQY0H1ovKh0bHXdiFF6ao'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'O1SxmXX8M8WxQY0H1ovKh0bHXdiFF6ao',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'search-publications
search-publications/*
documents',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -35,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Treaty',
    'visibility' => 1,
  );

  $export['facetapi-Pg30Pc0KVb1ixI192kdMOYYpptaM7w81'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'Pg30Pc0KVb1ixI192kdMOYYpptaM7w81',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'informea_theme',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-bhF7dlwZfRYrATVWsYC6eOvTl9pFOHHh'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'bhF7dlwZfRYrATVWsYC6eOvTl9pFOHHh',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'search-legislation
search-legislation/*',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -38,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Type of text',
    'visibility' => 1,
  );

  $export['facetapi-fdq04xNUyxSV1CkoyeTHIwwlufwxjcFK'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'fdq04xNUyxSV1CkoyeTHIwwlufwxjcFK',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'search-court-decisions
search-court-decisions/*',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -42,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Region',
    'visibility' => 1,
  );

  $export['facetapi-jX6n57R09128yKk8mDTq4yM84f6PAh5a'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'jX6n57R09128yKk8mDTq4yM84f6PAh5a',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'search-court-decisions
search-court-decisions/*',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -43,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Country',
    'visibility' => 1,
  );

  $export['facetapi-lFTDOmrsVmQmRqG1yhvhkLE1HBeKji6v'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'lFTDOmrsVmQmRqG1yhvhkLE1HBeKji6v',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'search-publications
search-publications/*',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -30,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Literature type',
    'visibility' => 1,
  );

  $export['facetapi-nH0H81P3pdN1dfvkdvCD5VKkmHgsDC6W'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'nH0H81P3pdN1dfvkdvCD5VKkmHgsDC6W',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'search-publications
search-publications/*',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -29,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Publication place',
    'visibility' => 1,
  );

  $export['facetapi-ngjcSTHvKkM3YrCBeABMwT0nTaX6fC4t'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'ngjcSTHvKkM3YrCBeABMwT0nTaX6fC4t',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'documents',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -26,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'InforMEA tags',
    'visibility' => 1,
  );

  $export['facetapi-p9FlWiab4gZsEGaV8liVtKqUrzwmczuq'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'p9FlWiab4gZsEGaV8liVtKqUrzwmczuq',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'search-publications
search-publications/*',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -27,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Territorial subdivision',
    'visibility' => 1,
  );

  $export['facetapi-qTurWYUYYufA4n4p1OFoxmFTW0m9G81J'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'qTurWYUYYufA4n4p1OFoxmFTW0m9G81J',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'search
search/*
search-bilateral-treaties
search-bilateral-treaties/*',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -45,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Country',
    'visibility' => 1,
  );

  $export['facetapi-rm0orTI2PzmJnpZ1x07XLj097DSEjQQJ'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'rm0orTI2PzmJnpZ1x07XLj097DSEjQQJ',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'search
search/*',
    'roles' => array(),
    'themes' => array(
      'informea_theme' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'informea_theme',
        'weight' => -48,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Type',
    'visibility' => 1,
  );

  return $export;
}
