<?php
/**
 * @file
 * Code for the informea_search feature.
 */

include_once 'informea_search.features.inc';

/**
 * Implements hook_views_pre_render().
 */
function informea_search_views_pre_render(&$view) {
  if ($view->name == 'informea_search') {
    module_load_include('inc', 'informea_search', 'informea_search.results');
    $group = new InforMEASearchResultsGrouping();
    $view->result = $group->getResults($view->result);
  }
}

/**
 * Implements hook_form_alter().
 */
function informea_search_form_search_form_alter(&$form, &$form_state) {
  $form['#method'] = 'post';
  $form['#action'] = url('search');
  $form['#submit'] = array('informea_search_form_search_form_submit');
}

function informea_search_form_search_form_submit($form, $form_state) {
  $input = $form_state['values']['keys'];
  drupal_goto('search/' . $input);
}


function informea_search_facet_items_alter(&$build, &$settings) {
  return;
  $t_active = isset($build['all_treaty']['#active']) && $build['all_treaty']['#active'] == 1;
  if ($settings->facet == 'type') {
    $build['all_treaty'] = array(
        '#markup' => 'Treaty',
        '#path' => 'search/alien',
        '#html' => FALSE,
        '#indexed_value' => 'all_treaty',
        '#count' => '1',
        '#active' => $t_active,
        '#item_parents' => array(),
        '#item_children' => array(),
        '#query' => array('f' => array())
    );


    $d_active = isset($build['all_decision']['#active']) && $build['all_decision']['#active'] == 1;
    $build['all_decision'] = array(
        '#markup' => 'Decisions / Resolutions',
        '#path' => 'search/alien',
        '#html' => FALSE,
        '#indexed_value' => 'decision',
        '#count' => '1',
        '#active' => $d_active,
        '#item_parents' => array(),
        '#item_children' => array(),
        '#query' => array('f' => array())
    );

    if($t_active) {
      if ($d_active) {
        $build['all_treaty']['#query']['f'] = array(99 => 'type:all_decision');
        $build['all_decision']['#query']['f'] = array(98 => 'type:all_treaty');
      }
      else {
        $build['all_treaty']['#query']['f'] = array();
        $build['all_decision']['#query']['f'] = array(
          98 => 'type:all_treaty',
          99 => 'type:all_decision'
        );
      }
    }
    else {
      if ($d_active) {
        $build['all_treaty']['#query']['f'] = array(
          98 => 'type:all_treaty',
          99 => 'type:all_decision'
        );
        $build['all_decision']['#query']['f'] = array();
      }
      else {
        $build['all_treaty']['#query']['f'] = array(98 => 'type:all_treaty');
        $build['all_decision']['#query']['f'] = array(99 => 'type:all_decision');
      }
    }

    unset($build['treaty_paragraph']);
    unset($build['decision_paragraph']);
    unset($build['event_calendar']);
    unset($build['treaty_article']);
    unset($build['action_plan']);
    unset($build['national_report']);
    unset($build['decision']);
    unset($build['treaty']);
  }
}

function informea_search_search_api_solr_query_alter(array &$call_args, SearchApiQueryInterface $query) {
  $pos = array_search('{!tag=facet:type}ss_type:"all_treaty"', $call_args['params']['fq']);
  if ($pos !== FALSE) {
    $call_args['params']['fq'][$pos] = '{!tag=facet:type}((ss_type:"treaty_article") OR (ss_type:"treaty_paragraph"))';
  }
  $pos = array_search('{!tag=facet:type}ss_type:"all_decision"', $call_args['params']['fq']);
  if ($pos !== FALSE) {
    $call_args['params']['fq'][$pos] = '{!tag=facet:type}((ss_type:"decision") OR (ss_type:"decision_paragraph"))';
  }
}

/**
* Implementation of hook_menu().
*/
function informea_search_menu() {
  $items['ajax/search/%'] = array(
    'page callback' => 'informea_search_ajax_get_ajax',
    'page arguments' => array(2),
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'delivery callback' => 'informea_search_ajax_callback',
  );

  return $items;
}

function informea_search_ajax_get_ajax($term) {
  $results = array(
    array (
      'category' => '',
      'label' => 'anders',
      'link' => '#',
      'value' => 'anders'
    ),
    array (
      'category' => '',
      'label' => 'andreas',
      'link' => '#',
      'value' => 'andreas'
    ),
    array (
      'category' => '',
      'label' => 'antal',
      'link' => '#',
      'value' => 'antal'
    ),
    array (
      'category' => 'Products',
      'label' => 'annhhx10',
      'link' => '#',
      'value' => 'annhhx10'
    ),
    array (
      'category' => 'Products',
      'label' => 'annkK12',
      'link' => '#',
      'value' => 'annkK12'
    ),
    array (
      'category' => 'Products',
      'label' => 'annttopC13',
      'link' => '#',
      'value' => 'annttopC13'
    ),
    array (
      'category' => 'People',
      'label' => 'andersandersson',
      'link' => '#',
      'value' => 'andersandersson'
    ),
    array (
      'category' => 'People',
      'label' => 'andreasandersson',
      'link' => '#',
      'value' => 'andreasandersson'
    ),
    array (
      'category' => 'People',
      'label' => 'andreasjohnson',
      'link' => '#',
      'value' => 'andreasjohnson'
    )
  );

  return $results;
}
