<?php

/**
 * @file leo_migrate.module
 */


/**
 * Common mappings for the Drupal 7 node migrations.
 */
class LeoNodeMigration extends DrupalNode7Migration {
  public function __construct(array $arguments) {
    parent::__construct($arguments);

    $this->addFieldMapping('title', 'title', FALSE);
    $this->addFieldMapping('body:language', 'body:language', FALSE);
  }

  public function map_source_term($source_tid, $taxonomy) {
    $mappings = array();
    $voc = taxonomy_vocabulary_machine_name_load($taxonomy);

    $q = db_select('taxonomy_term_data', 't')->fields('t');
    $rows = $q->execute()->fetchAllAssoc('tid');
    foreach($rows as $term) {
      $mappings[$term->vid][strtolower($term->name)] = $term->tid;
    }

    $query = Database::getConnection('default', $this->sourceConnection)
      ->select('taxonomy_term_data', 't')
      ->fields('t', array('name'))
      ->condition('tid', $source_tid);

    $source_english = $query->execute()->fetchField();

    if (!empty($mappings[$voc->vid][strtolower($source_english)])) {
      return $mappings[$voc->vid][strtolower($source_english)];
    }

    return NULL;
  }
}

/**
 * Log system for the leo_migrate migrations.
 *
 * @param string $message
 *   Log message
 * @param int $severity
 *    See MigrationBase::MESSAGE_* constants
 */
function leo_migrate_log($message, $severity = MigrationBase::MESSAGE_INFORMATIONAL) {
  if (function_exists('drush_log')) {
    $status = 'status';
    switch($severity) {
      case MigrationBase::MESSAGE_ERROR:
        $status = 'error';
        break;
      case MigrationBase::MESSAGE_WARNING:
        $status = 'warning';
        break;
      case MigrationBase::MESSAGE_NOTICE:
        $status = 'notice';
        break;
    }
    drush_log($message, $status);
    return;
  }
}
