<?php
/**
 * @file
 * Code for the ecolex feature.
 */

include_once 'ecolex.features.inc';

/**
 * Implements hook_menu().
 */
function ecolex_menu() {
  return array(
    // ecolex/ajax/taxonomy/234/legislation/1
    'ecolex/ajax/%/%/%/%' => array(
      'title' => 'ECOLEX content loaded via ajax',
      'page callback' => 'ecolex_ajax_content',
      'page arguments' => array(2, 3, 4, 5, 6),
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
    ),
  );
}

/**
 * Import default Ecolex Thesaurus.
 */
function ecolex_create_default_thesaurus_terms() {
  menu_rebuild();
  $path = drupal_get_path('module', 'ecolex') . DIRECTORY_SEPARATOR . 'data' . DIRECTORY_SEPARATOR . 'thesaurus.json';
  if (is_readable($path)) {
    if($voc = taxonomy_vocabulary_machine_name_load('thesaurus_ecolex')) {
      if ($json = json_decode(file_get_contents($path))) {
        foreach ($json as $term) {
          $existing = taxonomy_get_term_by_name($term, 'thesaurus_ecolex');
          if(empty($existing)) {
            taxonomy_term_save((object) array(
              'name' => $term,
              'vid' => $voc->vid
            ));
          }
          else {
            drupal_set_message("$term already exists ...", 'warning');
          }
        }
      }
    }
  }
}

/**
 * Import default keywords from Ecolex.
 */
function ecolex_create_default_keywords_terms() {
  $path = drupal_get_path('module', 'ecolex') . DIRECTORY_SEPARATOR . 'data' . DIRECTORY_SEPARATOR . 'keywords.json';
  if (is_readable($path)) {
    if($voc = taxonomy_vocabulary_machine_name_load('keywords')) {
      if ($json = json_decode(file_get_contents($path))) {
        foreach ($json as $term) {
          $existing = taxonomy_get_term_by_name($term, 'keywords');
          if(empty($existing)) {
            taxonomy_term_save((object) array(
              'name' => $term,
              'vid' => $voc->vid
            ));
          }
          else {
            drupal_set_message("$term already exists ...", 'warning');
          }
        }
      }
    }
  }
}

/**
 * Implements hook_form_node_form_alter().
 *
 * {@inheritdoc}
 */
function ecolex_form_node_form_alter(&$form, &$form_state) {
  if (!empty($form['field_informea_tags'][LANGUAGE_NONE]['#options'])) {
    $options =& $form['field_informea_tags'][LANGUAGE_NONE]['#options'];
    unset($options['_none']);
    foreach($options as &$value) {
      $value = preg_replace('/^\-*/', '', $value);
    }
    asort($options);
  }
}

function ecolex_ajax_content($context, $item, $type, $page = 0, $sid = '') {
  $data = ecolex_remote_content($context, $item, $type, $page, $sid);
  print $data;
  drupal_exit();
}


function ecolex_remote_url($context, $item, $type) {
  module_load_include('inc', 'ecolex', 'ecolex.parser');
  $base_url = NULL;
  $base_url = 'http://www.ecolex.org/ecolex/ledge/view/SearchResults';
  $base_url .= '?';
  $base_url .= 'sortField=searchDate';
  switch ($context) {
    case 'taxonomy':
      $t = taxonomy_term_load($item);
      $search = str_replace(' ', '+', $t->name_original);
      $search = str_replace('&', '%26', $search);
      $base_url .= format_string('&keyword=%22!keyword%22', array('!keyword' => $search));
      break;
    case 'country':
      $c = node_load($item);
      $search = str_replace(' ', '+', $c->title_original);
      $search = str_replace('&', '%26', $search);
      $base_url .= format_string('&country=%22!country%22', array('!country' => $search));
      break;
  }
  switch($type) {
    case 'treaties':
      $base_url .= '&screen=Treaties&index=treaties';
      break;
    case 'legislation':
      $base_url .= '&screen=Legislation&index=documents';
      break;
    case 'literature':
      $base_url .= '&screen=Literature&index=literature';
      break;
    case 'courtdecisions':
      $base_url .= '&screen=CourtDecisions&index=courtdecisions';
      break;
  }
  return $base_url;
}

function ecolex_remote_content($context, $item, $type, $page = 0, $sid = '') {
  module_load_include('inc', 'ecolex', 'ecolex.parser');
  $output = NULL;
  $base_url = NULL;
  $base_url = 'http://www.ecolex.org/ecolex/ledge/view/SearchResults';
  if (!empty($sid)) {
    // ;DIDPFDSIjsessionid=9DED006886116382A8E145E725EE9D44?
    $base_url .= $sid;
  }
  else {
    $base_url .= '?';
  }
  $base_url .= 'sortField=searchDate';
  switch ($context) {
    case 'taxonomy':
      $t = taxonomy_term_load($item);
      $search = str_replace(' ', '+', $t->name_original);
      $search = str_replace('&', '%26', $search);
      $base_url .= format_string('&keyword="!keyword"', array('!keyword' => $search));
      break;
    case 'country':
      $c = node_load($item);
      $search = str_replace(' ', '+', $c->title_original);
      $search = str_replace('&', '%26', $search);
      $base_url .= format_string('&country="!country"', array('!country' => $search));
      break;
  }
  switch($type) {
    case 'treaties':
      $base_url .= '&screen=Treaties&index=treaties';
      break;
    case 'legislation':
      $base_url .= '&screen=Legislation&index=documents';
      break;
    case 'literature':
      $base_url .= '&screen=Literature&index=literature';
      break;
    case 'courtdecisions':
      $base_url .= '&screen=CourtDecisions&index=courtdecisions';
      break;
  }
  $parser = new EcolexParser($base_url);
  $data = $parser->get_content();
  $data .= l(t('View more results on ECOLEX website'), $base_url, array('attributes' => array('class' => array('ecolex-link'), 'target' => '_blank')));
  return $data;
}


function ecolex_legislation_load_nid_by_faolexid($faolexId) {
  $q = db_select('field_data_field_original_id')->fields(NULL, array('entity_id'));
  $q->condition('bundle', 'legislation');
  $q->condition('field_original_id_value', $faolexId);
  $q->condition('entity_type', 'node');
  return $q->execute()->fetchField();
}