<?php
/**
 * @file
 * Code for the ecolex feature.
 */

include_once 'ecolex.features.inc';

/**
 * Implements hook_menu().
 */
function ecolex_menu() {
  return array(
    // ecolex/ajax/taxonomy/234/legislation/1
    'ecolex/ajax/%/%/%/%' => array(
      'title' => 'ECOLEX content loaded via ajax',
      'page callback' => 'ecolex_ajax_content',
      'page arguments' => array(2, 3, 4, 5, 6),
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
    ),
  );
}

/**
 * Import default Ecolex Thesaurus.
 */
function ecolex_create_default_thesaurus_terms() {
  menu_rebuild();
  $path = drupal_get_path('module', 'ecolex') . DIRECTORY_SEPARATOR . 'data' . DIRECTORY_SEPARATOR . 'thesaurus.json';
  if (is_readable($path)) {
    if($voc = taxonomy_vocabulary_machine_name_load('thesaurus_ecolex')) {
      if ($json = json_decode(file_get_contents($path))) {
        foreach ($json as $term) {
          $existing = taxonomy_get_term_by_name($term, 'thesaurus_ecolex');
          if(empty($existing)) {
            taxonomy_term_save((object) array(
              'name' => $term,
              'vid' => $voc->vid
            ));
          }
          else {
            drupal_set_message("$term already exists ...", 'warning');
          }
        }
      }
    }
  }
}

/**
 * Import default keywords from Ecolex.
 */
function ecolex_create_default_keywords_terms() {
  $path = drupal_get_path('module', 'ecolex') . DIRECTORY_SEPARATOR . 'data' . DIRECTORY_SEPARATOR . 'keywords.json';
  if (is_readable($path)) {
    if($voc = taxonomy_vocabulary_machine_name_load('keywords')) {
      if ($json = json_decode(file_get_contents($path))) {
        foreach ($json as $term) {
          $existing = taxonomy_get_term_by_name($term, 'keywords');
          if(empty($existing)) {
            taxonomy_term_save((object) array(
              'name' => $term,
              'vid' => $voc->vid
            ));
          }
          else {
            drupal_set_message("$term already exists ...", 'warning');
          }
        }
      }
    }
  }
}

/**
 * Implements hook_form_node_form_alter().
 *
 * {@inheritdoc}
 */
function ecolex_form_node_form_alter(&$form, &$form_state) {
  if (!empty($form['field_informea_tags'][LANGUAGE_NONE]['#options'])) {
    $options =& $form['field_informea_tags'][LANGUAGE_NONE]['#options'];
    unset($options['_none']);
    foreach($options as &$value) {
      $value = preg_replace('/^\-*/', '', $value);
    }
    asort($options);
  }
}

function ecolex_ajax_content($context, $item, $type, $page = 0, $sid = '') {
  $data = ecolex_remote_content($context, $item, $type, $page, $sid);
  print $data;
  drupal_exit();
}


function ecolex_remote_url($context, $item, $type) {
  module_load_include('inc', 'ecolex', 'ecolex.parser');
  $base_url = NULL;
  $base_url = 'http://www.ecolex.org/ecolex/ledge/view/SearchResults';
  $base_url .= '?';
  $base_url .= 'sortField=searchDate';
  switch ($context) {
    case 'taxonomy':
      $t = taxonomy_term_load($item);
      $search = str_replace(' ', '+', $t->name_original);
      $search = str_replace('&', '%26', $search);
      $base_url .= format_string('&keyword=%22!keyword%22', array('!keyword' => $search));
      break;
    case 'country':
      $c = node_load($item);
      $search = str_replace(' ', '+', $c->title_original);
      $search = str_replace('&', '%26', $search);
      $base_url .= format_string('&country=%22!country%22', array('!country' => $search));
      break;
  }
  switch($type) {
    case 'treaties':
      $base_url .= '&screen=Treaties&index=treaties';
      break;
    case 'legislation':
      $base_url .= '&screen=Legislation&index=documents';
      break;
    case 'literature':
      $base_url .= '&screen=Literature&index=literature';
      break;
    case 'courtdecisions':
      $base_url .= '&screen=CourtDecisions&index=courtdecisions';
      break;
  }
  return $base_url;
}

function ecolex_remote_content($context, $item, $type, $page = 0, $sid = '') {
  module_load_include('inc', 'ecolex', 'ecolex.parser');
  $output = NULL;
  $base_url = NULL;
  $base_url = 'http://www.ecolex.org/ecolex/ledge/view/SearchResults';
  if (!empty($sid)) {
    // ;DIDPFDSIjsessionid=9DED006886116382A8E145E725EE9D44?
    $base_url .= $sid;
  }
  else {
    $base_url .= '?';
  }
  $base_url .= 'sortField=searchDate';
  switch ($context) {
    case 'taxonomy':
      $t = taxonomy_term_load($item);
      $search = str_replace(' ', '+', $t->name_original);
      $search = str_replace('&', '%26', $search);
      $base_url .= format_string('&keyword="!keyword"', array('!keyword' => $search));
      break;
    case 'country':
      $c = node_load($item);
      $search = str_replace(' ', '+', $c->title_original);
      $search = str_replace('&', '%26', $search);
      $base_url .= format_string('&country="!country"', array('!country' => $search));
      break;
  }
  switch($type) {
    case 'treaties':
      $base_url .= '&screen=Treaties&index=treaties';
      break;
    case 'legislation':
      $base_url .= '&screen=Legislation&index=documents';
      break;
    case 'literature':
      $base_url .= '&screen=Literature&index=literature';
      break;
    case 'courtdecisions':
      $base_url .= '&screen=CourtDecisions&index=courtdecisions';
      break;
  }
  $parser = new EcolexParser($base_url);
  $data = $parser->get_content();
  $data .= l(t('View more results on ECOLEX website'), $base_url, array('attributes' => array('class' => array('ecolex-link'), 'target' => '_blank')));
  return $data;
}


function ecolex_treaty_load_nid_by_faolexid($faolexId) {
  $q = db_select('field_data_field_original_id')->fields(NULL, array('entity_id'));
  $q->condition('bundle', 'treaty');
  $q->condition('field_original_id_value', $faolexId);
  $q->condition('entity_type', 'node');
  return $q->execute()->fetchField();
}

function ecolex_legislation_load_nid_by_faolexid($faolexId) {
  $q = db_select('field_data_field_original_id')->fields(NULL, array('entity_id'));
  $q->condition('bundle', 'legislation');
  $q->condition('field_original_id_value', $faolexId);
  $q->condition('entity_type', 'node');
  return $q->execute()->fetchField();
}

function ecolex_literature_load_nid_by_faolexid($faolexId) {
  $q = db_select('field_data_field_original_id')->fields(NULL, array('entity_id'));
  $q->condition('bundle', 'literature');
  $q->condition('field_original_id_value', $faolexId);
  $q->condition('entity_type', 'node');
  return $q->execute()->fetchField();
}

function ecolex_get_legislation_types_in_use() {
  // SELECT field_type_of_text_tid FROM field_data_field_type_of_text WHERE bundle = 'legislation' GROUP BY field_type_of_text_tid;
  $query = db_select('field_data_field_type_of_text')->fields(NULL, array('field_type_of_text_tid'));
  $query->condition('bundle', 'legislation');
  $query->groupBy('field_type_of_text_tid');
  return $query->execute()->fetchCol();
}


function ecolex_get_court_decisions_types_in_use() {
  $query = db_select('field_data_field_type_of_text')->fields(NULL, array('field_type_of_text_tid'));
  $query->condition('bundle', 'court_decisions');
  $query->groupBy('field_type_of_text_tid');
  return $query->execute()->fetchCol();
}

function ecolex_get_court_decisions_keywords_in_use($country = NULL) {
  return thesaurus_get_tags_in_use('field_ecolex_keywords', 'court_decisions', $country);
}

function ecolex_get_legislations_keywords_in_use($country = NULL) {
  return thesaurus_get_tags_in_use('field_ecolex_keywords', 'legislation', $country);
}

/**
 * Assign to node in field_informea_tags the LEO terms extracted from
 * field_ecolex_keywords based on the VocBench ECOLEX-LEO mappings.
 *
 * @param \stdClass $node Node with field_ecolex_keywords and field_informea_tags
 * @return true if node was changed and requires saving
 */
function ecolex_nod_map_ecolex_term($node) {
  $ret = false;
  $wrapper = entity_metadata_wrapper('node', $node->nid);
  $ecolex = $wrapper->field_ecolex_keywords->value();
  if (count($ecolex)) {
    $leo = $node->field_informea_tags[LANGUAGE_NONE];
    if ($leo != null) {
      array_walk($leo, function (&$v) {
        $v = $v['tid'];
      });
    }
    else {
      $leo = array();
    }
    foreach ($ecolex as $term) {
      $twr = entity_metadata_wrapper('taxonomy_term', $term);
      $mapped_terms = ThesaurusMapping::mapEcolexTermToLEO($twr->label());
      foreach($mapped_terms as $leo_tid) {
        // Append new terms if they do not already exist
        if (!in_array($leo_tid, $leo)) {
          $node->field_informea_tags[LANGUAGE_NONE][] = array('tid' => $leo_tid);
          $ret = true;
        }
      }
    }
  }
  return $ret;
}