<?php


function ws_provider_install() {
  ws_provider_update_7001();
}

/**
 * Decrease module's weight to capture hook_node_view() first
 */
function ws_provider_update_7001() {
  db_update('system')
    ->fields(array('weight' => -10))
    ->condition('name', 'osha_tmgmt', '=')
    ->execute();
}

/**
 * install new ws_provider_decisions view
 */
function ws_provider_update_7002() {
  features_revert_module('ws_provider');
}
