<?php
/**
 * @file
 * Code for the Country feature.
 */

include_once 'country.features.inc';

/**
 *  Implements hook_url_inbound_alter().
 */
function country_url_inbound_alter(&$path, $original_path, $path_language) {
  if($node = country_url_match_node($path)) {
    $path = 'node/' . $node->nid;
  }
}

function country_url_match_node($path) {
  module_load_include('inc', 'country', 'country.api');
  if (arg(0, $path) == 'countries') {
    if ($node = country_load_by_iso2(arg(1, $path))) {
      return $node;
    }
  } else if(strlen(arg(0, $path)) == 2) { // Assume language prefix @todo enhance
    if (arg(1, $path) == 'countries') {
      if ($node = country_load_by_iso2(arg(2, $path))) {
        return $node;
      }
    }
  }
  return FALSE;
}

function country_url_context($path) {
  $path = preg_replace('/([A-Za-z]{2})?\/?countries\/[A-Za-z]{2}\/?/', '', $path);
  $parts = explode('/', $path);
  return $parts[0];
}

/**
 *  Implements hook_node_view().
 */
function country_node_view($node, $view_mode, $langcode) {
  if($node->type == 'country' && $view_mode == 'full') {
    $context = country_url_context(request_path());
    if(empty($context)) {
      $context = 'map';
    }
    $node->context = $context;
    switch($context) {
      case 'map':
        // Adds the amCharts JavaScript files to the page.
        drupal_add_js('https://maps.googleapis.com/maps/api/js?v=3.exp', 'external');
        // Adds the country JavaScript file to the page.
        drupal_add_js(drupal_get_path('module', 'country') . '/js/map.js');
        $view = country_get_view_country_related_content($node->nid, 'page_geographical_site');
        $node->content['context'] = array(
          0 => array(
            '#type' => 'item', '#weight' => 10, '#markup' => '<div id="map-canvas" style="height: 400px;margin: 0px;padding: 0px"></div>',
          ),
          1 => array(
            '#type' => 'item', '#weight' => 20, '#markup' => $view->render(),
          ),
        );
        break;

      case 'national-reports':
        $view = country_get_view_country_related_content($node->nid, 'page_national_report');
        $node->content['context'] = array(
          '#type' => 'item', '#weight' => 10, '#markup' => $view->render(),
        );
        break;

      case 'court-decisions':
        $view = country_get_view_country_related_content($node->nid, 'page_court_decisions');
        $node->content['context'] = array(
          '#type' => 'item', '#weight' => 10, '#markup' => $view->render(),
        );
        break;

      case 'legislation':
        module_load_include('inc', 'country', 'country.forms');
        // Adds the amCharts JavaScript files to the page.
        drupal_add_js('http://cdn.amcharts.com/lib/3/amcharts.js', 'external');
        drupal_add_js('http://cdn.amcharts.com/lib/3/serial.js', 'external');
        drupal_add_js('http://cdn.amcharts.com/lib/3/themes/light.js', 'external');
        // Adds the country JavaScript file to the page.
        drupal_add_js(drupal_get_path('module', 'country') . '/js/country.js');
        $node->content['context'] = array(
          0 => array(
            '#type' => 'item', '#weight' => 10, '#markup' => '<div class="well"><div id="chart-bar"></div></div><!-- .well -->',
          ),
          1 => drupal_get_form('country_legislation_filter_form'),
        );
        break;

      case 'literature':
        module_load_include('inc', 'country', 'country.forms');
        // Adds the amCharts JavaScript files to the page.
        drupal_add_js('http://cdn.amcharts.com/lib/3/amcharts.js', 'external');
        drupal_add_js('http://cdn.amcharts.com/lib/3/serial.js', 'external');
        drupal_add_js('http://cdn.amcharts.com/lib/3/themes/light.js', 'external');
        // Adds the country JavaScript file to the page.
        drupal_add_js(drupal_get_path('module', 'country') . '/js/country.js');
        $node->content['context'] = array(
          0 => array(
            '#type' => 'item', '#weight' => 10, '#markup' => '<div class="well"><div id="chart-bar"></div></div><!-- .well -->',
          ),
          1 => drupal_get_form('country_literature_filter_form'),
        );
        break;
    }
  }
}

function country_country_contextual_menu_alter(&$contextual_menu, $node) {
  $ret = array();
  if ($node->type == 'country') {
    $uri = url(drupal_get_path_alias('node/' . $node->nid), array('absolute' => TRUE));
    $links = array(
      'map' => t('Map <span class="badge">!count</span>', array( '!count' => 56 )),
      'parties' => t('Membership <span class="badge">!count</span>', array( '!count' => 0 )),
      'action-plans' => t('Action plans <span class="badge">!count</span>',
        array('!count' => country_get_view_country_related_content_count($node->nid, 'page_action_plan'))
      ),
      'national-reports' => t('National reports <span class="badge">!count</span>',
        array('!count' => country_get_view_country_related_content_count($node->nid, 'page_national_report'))
      ),
      'legislation' => t('Law <span class="badge">!count</span>',
        array('!count' => country_get_view_country_related_content_count($node->nid, 'page_legislation'))
      ),
      'literature' => t('Literature <span class="badge">!count</span>',
        array('!count' => country_get_view_country_related_content_count($node->nid, 'page_literature'))
      ),
      'court-decisions' => t('Court decisions <span class="badge">!count</span>',
        array('!count' => country_get_view_country_related_content_count($node->nid, 'page_court_decisions'))
      ),
    );

    foreach($links as $path => $title) {
      $link = array(
        '#type' => 'link',
        '#title' => $title,
        '#href' => $uri . '/' . $path,
        '#attributes' => array( 'class' => array( 'list-group-item' ) ),
        '#options' => array( 'html' => TRUE ),
        '#active' => FALSE,
      );
      if (isset($node->context) && $node->context == $path) {
        $link['#attributes']['class'][] = 'active';
      }
      $contextual_menu[] = $link;
    }
  }
  return $ret;
}


function country_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  if (isset($router_item['page_arguments'][0]->type) && $router_item['page_arguments'][0]->type == 'country') {
    $context_menu = array();
    $node = $router_item['page_arguments'][0];
    drupal_alter('country_contextual_menu', $context_menu, $node);
    $data['tabs'][1] = array(
      'count' => count($context_menu),
      'output' => $context_menu,
    );
  }
}
