<?php
/**
 * @file
 * Code for the thesaurus feature.
 */

include_once 'thesaurus.features.inc';

require_once 'includes/export.inc';
require_once 'includes/vocbench.inc';
require_once 'thesaurus.foamtree.inc';

if(!function_exists('slugify')) {
  function slugify($phrase, $maxLength = 50) {
    $result = strtolower($phrase);
    $result = preg_replace("/[^a-z0-9\s-]/", "", $result);
    $result = trim(preg_replace("/[\s-]+/", " ", $result));
    $result = preg_replace("/\s/", "-", $result);
    return $result;
  }
}

function thesaurus_menu() {
  return array(
    'export/thesaurus.rdf' => array(
      'title' => 'Export in RDF',
      'page callback' => 'thesaurus_export_rdf',
      'delivery callback' => 'thesaurus_menu_export_rdf',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
    ),
    'export/thesaurus.xls' => array(
      'title' => 'Export in MS Excel',
      'page callback' => 'thesaurus_export_xls',
      'delivery callback' => 'thesaurus_menu_export_xls',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
    )
  );
}

/**
 * Implements hook_libraries_info().
 */
function thesaurus_libraries_info() {
  return array(
    'PHPExcel' => array(
      'name' => 'PHPExcel',
      'vendor url' => 'http://phpexcel.codeplex.com/',
      'download url' => 'https://github.com/PHPOffice/PHPExcel',
      'version callback' => 'thesaurus_get_library_version',
      'path' => 'Classes',
      'files' => array(
        'php' => array(
          'PHPExcel.php',
        ),
      ),
    ),
  );
}

function thesaurus_block_info() {
  $blocks = array();
  $blocks['terms-listing'] = array(
    'info' => t('Terms listing with 2 tabs.'),
    'status' => 1,
    'region' => '-1',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => '',
  );
  $blocks['thesaurus-treaties'] = array(
    'info' => t('Treaties tagged with current term'),
    'status' => 1,
    'region' => '-1',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => '',
  );
  $blocks['thesaurus-bilateral-treaties'] = array(
    'info' => t('Bilateral treaties tagged with current term'),
    'status' => 1,
    'region' => '-1',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => '',
  );
  $blocks['thesaurus-disclaimer'] = array(
    'info' => t('Thesaurus disclaimer'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 1,
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'pages' => '',
  );
  return $blocks;
}

function thesaurus_get_disclaimer_block() {
  $block = [];
  $node = null;
  $faolex_node = false;
  $ecolex_node = false;
  if ($node = menu_get_object()) {
    if ($node->type == 'legislation') {
      $faolex_node = true;
    }
    if ($node->type == 'literature') {
      $ecolex_node = true;
    }
    if ($node->type == 'treaty') {
      $wrapper = entity_metadata_wrapper('node', $node);
      if ($source = @$wrapper->field_data_source->value()[0]->tid) {
        if ($source == DATA_SOURCE_ECOLEX) {
          $ecolex_node = true;
        }
      }
    }
  }

  if ($faolex_node || (arg(0) == 'search-legislation') || (arg(0)=='taxonomy' && arg(3) == 'legislation')) {
    $block['subject'] = '<none>';
    $block['content'] = '<div><p style="text-align:center"><span class="faolex-logo"></span>This content is exclusively provided by <a href="http://www.fao.org/" target="_blank">FAO</a> / <a href="http://www.fao.org/faolex/en" target="_blank">FAOLEX</a> / <a href="http://www.ecolex.org" target="_blank">ECOLEX</a><span class="ecolex-logo"></span></p></div>';
  }
  else if ($ecolex_node || arg(0) == 'search-bilateral-treaties' || (arg(0)=='taxonomy' && arg(3) == 'bilateral-treaties')) {
    $block['subject'] = '<none>';
    $block['content'] = '<div><p style="text-align:center"><span class="ecolex-logo"></span>This content is exclusively provided <a href="http://www.ecolex.org" target="_blank">ECOLEX</a>.</p></div>';
  }
  return $block;
}
/**
 * Implements hook_block_view().
 */
function thesaurus_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'thesaurus-disclaimer':
      $block = thesaurus_get_disclaimer_block();
      break;
    case 'terms-listing':
      $block['subject'] = 'Terms listing with 2 tabs';
      $block['content'] = thesaurus_terms_listing_block_content();
      break;
    case 'thesaurus-treaties':
    case 'thesaurus-bilateral-treaties':
      $block['subject'] = t('Treaties tagged with current term');
      module_load_include('inc', 'thesaurus', 'thesaurus.related');
      if (arg(0) == 'taxonomy' && arg(1) == 'term' && is_numeric(arg(2))) {
        $term = taxonomy_term_load(arg(2));
      }
      if (!empty($term)) {
        $type = ($delta == 'thesaurus-treaties') ? 'multilateral' : 'bilateral';
        $dp = new InforMEAThesaurusTermRelatedContent($term);
        $related_data = $dp->getRelatedContent($term, $type);
        $related_content = InforMEAThesaurusTermRelatedContent::view($term, $related_data['treaties']);
        $block['content'] = array(
          '#markup' => drupal_render($related_content),
          '#weight' => 10,
        );
      }
      break;
  }
  return $block;
}

function thesaurus_terms_listing_block_content() {
  drupal_add_js(drupal_get_path('module', 'thesaurus') . '/js/jquery.fastLiveFilter.js');
  drupal_add_js(drupal_get_path('module', 'thesaurus') . '/js/terms.js');
  $terms_atoz = array();
  $terms_hierarchical = array();
  $voc = taxonomy_vocabulary_machine_name_load('thesaurus_informea');

  // AtoZ
  $q = new EntityFieldQuery();
  $tids = $q->entityCondition('entity_type', 'taxonomy_term')
    ->propertyCondition('vid', $voc->vid)
    ->fieldOrderBy('name_field', 'value', 'ASC')
    ->execute();
  if (!empty($tids['taxonomy_term'])) {
    $terms_atoz = taxonomy_term_load_multiple(array_keys($tids['taxonomy_term']));
  }

  // Hierarchical
  $q = db_select('taxonomy_term_hierarchy', 'a')
    ->fields('a', array('tid'));
  $q->innerJoin('taxonomy_term_data', 'b', 'a.tid = b.tid');
  $q->condition('b.vid', $voc->vid)
    ->condition('a.parent', 0);
  $tids = $q->execute()->fetchCol();

  foreach($tids as $tid) {
    $term = taxonomy_term_load($tid);
    $children = taxonomy_get_tree($voc->vid, $tid);
    $term->children = thesaurus_get_nested_tree($children, NULL, $tid);
    $terms_hierarchical[$tid] = $term;
  }
  return theme('terms-listing', array('terms_atoz' => $terms_atoz, 'terms_hierarchical' => $terms_hierarchical));
}

function thesaurus_menu_export_rdf() {
  if ($xml = thesaurus_export_rdf()) {
    $filename = sprintf('thesaurus-%s.rdf', date('Ymd-Hi'));
    header("Content-Disposition: attachment; filename=$filename;");
    header('Content-type: application/rdf+xml; charset=utf-8');
    print $xml;
    drupal_exit();
    return;
  }
  // Fail with error
  drupal_page_header();
  header("HTTP/1.1 500 Internal Server Error", true, 500);
  watchdog('thesaurus', 'An error has occurred while generating the thesaurus RDF xml');
  // Perform end-of-request tasks.
  drupal_page_footer();
  print 'An error has occurred while generating the response. Please contact technical support';
  drupal_exit();
}


function thesaurus_theme() {
  return array(
    'term-tree' => array(
      'render element' => 'element',
      'template' => 'templates/term-tree',
      'variables' => array('term' => FALSE),
      'path' => drupal_get_path('module', 'thesaurus'),
    ),
    'term-hierarchy' => array(
      'render element' => 'element',
      'template' => 'templates/term-hierarchy',
      'variables' => array('parents' => array(), 'children' => array(), 'term' => FALSE),
      'path' => drupal_get_path('module', 'thesaurus'),
    ),
    'terms' => array(
      'render element' => 'element',
      'template' => 'templates/terms',
      'variables' => array('substantives' => array()),
      'path' => drupal_get_path('module', 'thesaurus'),
    ),
    'terms-listing' => array(
      'template' => 'templates/terms-listing',
      'variables' => array('terms_hierarchical' => array()),
      'path' => drupal_get_path('module', 'thesaurus'),
    ),
  );
}

function _thesaurus_get_related_content_count($term, $bundle) {
  $select = db_select('field_data_field_informea_tags', 'a')->fields('a')->condition('field_informea_tags_tid', $term->tid);
  switch ($bundle) {
    case 'treaty':
      // ToDo: find a better solution
      $dp = new InforMEAThesaurusTermRelatedContent($term);
      $related_data = $dp->getRelatedContent($term, 'multilateral');
      return !empty($related_data['treaties']) ? count($related_data['treaties']) : 0;

    case 'bilateral-treaties':
      $bilateral_treaties = _informea_search_get_treaties_by_data_source(DATA_SOURCE_ECOLEX);
      if (!empty($bilateral_treaties)) {
        return $select->condition('entity_id', $bilateral_treaties, 'IN')->execute()->rowCount();
      }
      return false;

    case 'court_decisions':
    case 'legislation':
    case 'literature':
    case 'document':
      return $select->condition('bundle', $bundle)->execute()->rowCount();

    default:
      return false;
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function thesaurus_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  if (arg(0) == 'taxonomy') {
    $voc = taxonomy_vocabulary_machine_name_load('thesaurus_informea');
    /** @var stdClass $term */
    if ($term = taxonomy_term_load(arg(2))) {
      if ($term->vid == $voc->vid) {
        $section = Thesaurus::getSection();

        $treatiesCount = _thesaurus_get_related_content_count($term, 'treaty');
        $bilateralTreatiesCount = _thesaurus_get_related_content_count($term, 'bilateral-treaties');
        $courtDecisionsCount = _thesaurus_get_related_content_count($term, 'court_decisions');
        $legislationsCount = _thesaurus_get_related_content_count($term, 'legislation');
        $publicationsCount = _thesaurus_get_related_content_count($term, 'literature') + _thesaurus_get_related_content_count($term, 'document');

        $menu_items = array(
          'default' => array(
            'data' => l(t('Multilateral treaties') . ' <span class="badge">' . $treatiesCount . '</span>', 'taxonomy/term/' . $term->tid, ['html' => true]),
            'role' => 'presentation',
          ),
          'bilateral-treaties' => array(
            'data' => l(t('Bilateral treaties') . ' <span class="badge">' . $bilateralTreatiesCount . '</span>', 'taxonomy/term/' . $term->tid . '/bilateral-treaties', ['html' => true]),
            'role' => 'presentation',
          ),
          'legislation' => array(
            'data' => l(t('Legislation') . ' <span class="badge">' . $legislationsCount . '</span>', 'taxonomy/term/' . $term->tid . '/legislation', ['html' => true]),
            'role' => 'presentation',
          ),
          'court-decisions' => array(
            'data' => l(t('Court decisions') . ' <span class="badge">' . $courtDecisionsCount . '</span>', 'taxonomy/term/' . $term->tid . '/court-decisions', ['html' => true]),
            'role' => 'presentation',
          ),
          'publications' => array(
            'data' => l(t('Publications') . ' <span class="badge">' . $publicationsCount . '</span>', 'taxonomy/term/' . $term->tid . '/publications', ['html' => true]),
            'role' => 'presentation',
          ),
        );
        $menu_items[$section]['class'] = array('active');
        $contextual_menu = array(
          '#theme' => 'item_list',
          '#attributes' => array('class' => array('nav', 'nav-tabs')),
          '#items' => $menu_items
        );
        $data['tabs'][1] = array(
          'count' => count($menu_items),
          'output' => $contextual_menu,
        );
      }
    }
  }
}

/************************************ </HOOKS> ********************************/

/**
 * Libraries API version callback.
 */
function thesaurus_get_library_version() {
  $library = libraries_load('PHPExcel');
  $changelog_file = $library['library path'] . '/changelog.txt';

  if (file_exists($changelog_file)) {
    $changelog = file_get_contents($changelog_file);
    $match = array(0 => 0, 1 => 'n/a');
    if (preg_match('/\d{4}-\d{2}-\d{2}\s+\(v([0-9\.]+)/', $changelog, $match)) {
      return $match[1];
    }
    elseif (preg_match('/@version\s+([0-9\.]+)/', $changelog, $match)) {
      return $match[1];
    }
  }
  return 'n/a';
}

function thesaurus_menu_export_xls() {
  thesaurus_export_xls();
}

function thesaurus_get_nested_tree($terms = array(), $max_depth = NULL, $parent = 0, $parents_index = array(), $depth = 0) {
  $return = array();
  foreach($terms as $term) {
    foreach($term->parents as $term_parent) {
      if ($term_parent == $parent) {
        $return[$term->tid] = $term;
      }
      else {
        $parents_index[$term_parent][$term->tid] = $term;
      }
    }
  }

  foreach($return as &$term) {
    if (isset($parents_index[$term->tid]) && (is_null($max_depth) || $depth < $max_depth)) {
      $term->children = thesaurus_get_nested_tree($parents_index[$term->tid], $max_depth, $term->tid, $parents_index, $depth + 1);
    }
  }
  return $return;
}

function thesaurus_url_term($term) {
  return url('taxonomy/term/' . $term->tid, array('absolute' => TRUE));
}

/**
 * Generate the RDF XML to export
 */
function thesaurus_export_rdf() {
  $export = new InforMEAThesaurusExportRDF();
  return $export->toXML();
}

function thesaurus_export_xls() {
  libraries_load('PHPExcel');
  $filename = sprintf('thesaurus-%s.xls', date('Ymd-Hi'));
  header("Content-Type: 'application/vnd.ms-excel'");
  header("Content-Disposition: attachment; filename=$filename;");
  InforMEAThesaurusExportXLS::toXLS();
}

function thesaurus_term_hierarchy($term) {
  if (!is_object($term) || empty($term->tid)) {
    $term = taxonomy_term_load($term);
  }
  $parents = taxonomy_get_parents($term->tid);
  $children = taxonomy_get_tree($term->vid, $term->tid, 1);
  return array(
    'parents' => $parents,
    'children' => $children,
  );
}

/**
 * Synchronize InforMEA Thesaurus (thesaurus_informea) with VocBench.
 *
 * @param bool|FALSE $force_update
 *   If TRUE, force all terms will to be updated, otherwise only those changed
 */
function thesaurus_informea_sync_vocbench($force_update = FALSE) {
  $no_updated = 0;
  $no_created = 0;
  $vocbench = thesaurus_load_informea_from_rdf();
  $terms = array();
  $sha_ones = array();
  foreach ($vocbench as $uri => $vb_term) {
    if (!in_array($vb_term->status, array('Validated', 'Published'))) {
      continue;
    }

    $term = thesaurus_term_load_by_uri($uri, 'thesaurus_informea');
    $original_sha = NULL;
    if (empty($term)) {
      $voc = taxonomy_vocabulary_machine_name_load('thesaurus_informea');
      $term = (object) array(
        'name' => $vb_term->name,
        'language' => 'en',
        'vid' => $voc->vid,
        'vocabulary_machine_name' => $voc->machine_name,
      );
      $term->field_taxonomy_term_uri[LANGUAGE_NONE][0]['url'] = $uri;
    }
    else {
      $original_sha = sha1(json_encode($term));
    }
    $terms[$uri] = $term;
    $sha_ones[$uri] = $original_sha;
  }

  foreach ($terms as $uri => $term) {
    $original_sha = $sha_ones[$uri];
    $vb_term = $vocbench[$uri];

    // Term name in english
    $term->name = $vb_term->name;

    // Term name
    foreach($vb_term->prefLabel as $language => $value) {
      if (!empty($value)) {
        $term->name_field[$language][0]['value'] = $value;
      }
    }

    // Definition
    if (!empty($vb_term->definition['en'][0])) {
      $term->description = $vb_term->definition['en'][0];
    }
    if (count($term->description_field) != count($vb_term->definition)) {
      $skip_description = FALSE;
      if (count($vb_term->definition) == 0) {
        if ($term->description_field['en'][0]['value'] == NULL) {
          /*
           * If the term has no description, $vb_term->definition is an empty array, but
           * $term->description_field has an element with NULL value. In this case
           * we do not want to change de term because it would be updated
           * though not necessary
           */
          $skip_description = TRUE;
        }
      }
      if (!$skip_description) {
        $term->description_field = array();
        foreach($vb_term->definition as $language => $values) {
          if (!empty($values[0])) {
            $term->description_field[$language][0]['value'] = $values[0];
          }
        }
      }
    }

    // Synonyms
//    if (count($term->field_term_synonyms) != count($vb_term->altLabel)) {
//      $term->field_term_synonyms = array();
//    }
    foreach($vb_term->altLabel as $language => $values) {
      if (!empty($values)) {
        if ($language != 'en') {
          $term->name_field[$language][0]['value'] = reset($values);
          array_shift($values);
        }
//        We don't have "synonyms" in INFORMEA so we leave this commented for now.
//        foreach ($values as $key => $syno) {
//          $term->field_term_synonyms[$language][$key]['value'] = $syno;
//        }
      }
    }
    // We don't have "Related from other thesauri" in INFORMEA so we leave this
    // commented for now.
/*
    // Related from other thesauri
    if (empty($term->field_term_related_uri[LANGUAGE_NONE]) || count($term->field_term_related_uri[LANGUAGE_NONE]) != count($vb_term->relatedMatch)) {
      $term->field_term_related_uri = array();
    }
    foreach($vb_term->relatedMatch as $i => $v) {
      $term->field_term_related_uri[LANGUAGE_NONE][$i]['url'] = $v;
    }
*/

    $sha = sha1(json_encode($term));
    if ($force_update || ($original_sha != $sha)) {
      $new = empty($term->tid);
      taxonomy_term_save($term);
      $translations = array();
      if (!empty($term->name_field)) {
        $translations = array_merge($translations, array_keys($term->name_field));
      }
      if (!empty($term->description_field)) {
        $translations = array_merge($translations, array_keys($term->description_field));
      }
      if (!empty($term->field_term_synonyms)) {
        $translations = array_merge($translations, array_keys($term->field_term_synonyms));
      }
      $languages = array_unique($translations);
      $translation_handler = entity_translation_get_handler('taxonomy_term', $term);
      foreach ($languages as $language) {
        if ($language == 'en' || $language == LANGUAGE_NONE) {
          continue;
        }
        $translation_handler->setTranslation(array(
          'translate' => 0,
          'status' => 1,
          'uid' => 1,
          'language' => $language,
          'source' => 'en',
        ));
        field_attach_update('taxonomy_term', $term);
      }
      watchdog('thesaurus', 'Updated term !tid: <a href="!turl">!name</a>, from VocBench: !vburl',
        array('!tid' => $term->tid, '!turl' => url('taxonomy/term/' . $term->tid), '!vburl' => $uri, '!name' => $term->name),
        WATCHDOG_INFO
      );
      if (function_exists('drush_log')) {
        drush_log(($new ? 'Create' : 'Update') . " term {$term->tid}: {$term->name}", "ok");
      }
      $new ? $no_created++ : $no_updated++;
    }
  }

  // After synchronization link parents & related terms
  foreach ($vocbench as $uri => $vb_term) {
    $ob = thesaurus_term_load_by_uri($uri, 'thesaurus_informea');
    if (!empty($vb_term->broader)) {
      $broader = thesaurus_term_load_by_uri($vb_term->broader, 'thesaurus_informea');
      if (empty($broader)) {
        watchdog('thesaurus', 'Cannot find parent term by URI: !buri',
          array('!buri' => $vb_term->broader),
          WATCHDOG_WARNING
        );
        continue;
      }
      if (empty($ob)) {
        watchdog('thesaurus', 'Cannot term by URI: !turi',
          array('!turi' => $uri),
          WATCHDOG_ERROR
        );
        continue;
      }

      $wrapper = entity_metadata_wrapper('taxonomy_term', $ob->tid);
      $parents = $wrapper->parent->value();
      if (empty($parents) || empty($parents[0]->tid) || $parents[0]->tid != $broader->tid) {
        $ob->parent = $broader->tid;
        taxonomy_term_save($ob);
        if (function_exists('drush_log')) {
          drush_log("Set '{$broader->name}' ({$broader->tid}) parent to '{$ob->name}' ({$ob->tid})", "ok");
        }
      }
    }
    if (!empty($vb_term->related)) {
      $ob->field_informea_tags[LANGUAGE_NONE] = array();
      foreach($vb_term->related as $rt_uri) {
        if ($related = thesaurus_term_load_by_uri($rt_uri, 'thesaurus_informea')) {
          $ob->field_informea_tags[LANGUAGE_NONE][] = array('tid' => $related->tid);
        }
      }
      taxonomy_term_save($ob);
    }
  }
  if (function_exists('drush_log')) {
    if ($no_created) {
      drush_log("Created {$no_created} terms.", "ok");
    }
    if ($no_updated) {
      drush_log("Updated {$no_updated} terms.", "ok");
    }
  }
}

/**
 * @deprecated
 */
function thesaurus_load_from_rdf_cached($rdf) {
  $thesaurus = NULL;
  $data = array();
  if ($cache = cache_get(__FUNCTION__, 'cache')) {
    $data = $cache->data;
  }
  if (!empty($data[$rdf])) {
    return $data[$rdf];
  }
  else {
    $thesaurus = thesaurus_load_from_rdf($rdf);
    if ($thesaurus) {
      $data[$rdf] = $thesaurus;
      cache_set(__FUNCTION__, $data, 'cache', time() + 3600);
    }
  }
  return $thesaurus;
}

/**
 * @deprecated
 */
function thesaurus_load_from_rdf($rdf) {
  if (!easyrdf()) {
    drupal_set_message(t('EasyRdf library is not available.'), 'error');
    return FALSE;
  }
  EasyRdf_Namespace::set('vb', 'http://art.uniroma2.it/ontologies/vocbench#');

  try {
    $graph = EasyRdf_Graph::newAndLoad($rdf);
    $resources = $graph->resources();
  }
  catch(Exception $e) {
    drupal_set_message("Failed to parse RDF file $rdf");
    return NULL;
  }

  $terms = array();
  /**
   * @var string $key
   * @var EasyRdf_Resource $resource
   */
  foreach ($resources as $key => $resource) {
    if ($resource->type() == 'skos:Concept') {
      $term = new stdClass();
      $term->name = NULL;
      $term->broader = NULL;
      $term->uri = $key;
      $term->prefLabel = array();
      $term->altLabel = array();
      $term->status = NULL;
      $term->definition = array();
      $term->relatedMatch = array();
      $term->related = array();

      // skos:broader
      if ($uri = $resource->get('skos:broader')) {
        $term->broader = (string) $uri;
      }

      // skos:prefLabel
      if ($prefLabels = $resource->allResources('skosxl:prefLabel')) {
        foreach($prefLabels as $prefLabel) {
          /** @var EasyRdf_Literal $lit */
          $lit = $prefLabel->get('skosxl:literalForm');
          $term->prefLabel[$lit->getLang()] = $lit->getValue();
        }
      }

      if (empty($term->prefLabel['en'])) {
        watchdog('thesaurus', 'Invalid VB term without english preffered label: !uri', array('!uri' => $key), WATCHDOG_WARNING);
      }
      else {
        $term->name = $term->prefLabel['en'];
      }

      // skos:altLabel
      if ($altLabels = $resource->allResources('skosxl:altLabel')) {
        foreach($altLabels as $altLabel) {
          /** @var EasyRdf_Literal $lit */
          $lit = $altLabel->get('skosxl:literalForm');
          $term->altLabel[$lit->getLang()][] = $lit->getValue();
        }
      }

      // skos:definition
      if ($definitions = $resource->allResources('skos:definition')) {
        foreach($definitions as $definition) {
          if ($value = $definition->get('rdf:value')) {
            $term->definition[$value->getLang()][] = $value->getValue();
          }
          else {
            // @todo: Ignore orphaned triple (missing rdf:value)
          }
        }
      }

      // skos:relatedMatch - external thesauri
      if ($relatedMatches = $resource->allResources('skos:relatedMatch')) {
        foreach($relatedMatches as $relatedMatch) {
          $term->relatedMatch[] = $relatedMatch->getUri();
        }
      }

      // skos:related - within same thesauri
      if ($related = $resource->allResources('skos:related')) {
        foreach($related as $r) {
          $term->related[] = $r->getUri();
        }
      }

      // vb:hasStatus
      if ($status = $resource->get('vb:hasStatus')) {
        $term->status = (string) $status;
      }


      if (empty($term->name) && !empty($term->altLabel['en'])) {
        $term->name = current($term->altLabel['en']);
      }

      if (!empty($term->name)) {
        $terms[$key] = $term;
      }
      else {
        watchdog('thesaurus', $key . ': Ignoring concept without name');
      }
    }
  }

  // Remove invalid parents (orphaned)
  foreach ($terms as $key => &$term) {
    if (isset($term->parent) && !isset($terms[$term->parent])) {
      unset($term->parent);
    }
  }
  return $terms;
}

function thesaurus_load_informea_from_rdf() {
  $url = variable_get('informea_vocbench_thesaurus_url', 'http://informea.org/sites/default/files/export/informea.rdf');
  return thesaurus_load_from_rdf_cached($url);
}

/**
 * Load a single term by its VocBench URI.
 *
 * @param string $uri
 * @param string $machine_name
 *
 * @return stdClass
 *  Taxonomy term loaded
 */
function thesaurus_term_load_by_uri($uri, $machine_name) {
  /** @var SelectQuery $q */
  $q = db_select('field_data_field_taxonomy_term_uri')->fields(NULL, array('entity_id'));
  $q->condition('field_taxonomy_term_uri_url', $uri);
  $q->condition('bundle', $machine_name);
  $q->condition('entity_type', 'taxonomy_term');
  if ($tid = $q->execute()->fetchField(0)) {
    return taxonomy_term_load($tid);
  }
  return NULL;
}

/**
 * Load a single term TID by its VocBench URI.
 *
 * @param string $uri
 * @param string $machine_name
 *
 * @return stdClass
 *  Taxonomy term tid
 */
function thesaurus_term_get_tid_by_uri($uri, $machine_name) {
  /** @var SelectQuery $q */
  $q = db_select('field_data_field_taxonomy_term_uri', 'a')->fields('a', array('entity_id'));
  $q->condition('field_taxonomy_term_uri_url', $uri);
  $q->condition('bundle', $machine_name);
  $q->condition('entity_type', 'taxonomy_term');
  $tid = $q->execute()->fetchField(0);
  return $tid != FALSE ? $tid : NULL;
}

/**
 * Implements hook_taxonomy_term_insert().
 */
function thesaurus_taxonomy_term_insert($term) {
  if ($term->vocabulary_machine_name == 'thesaurus_informea') {
    // Set the term path alias
    $term->path['pathauto'] = FALSE;
    $path = $term->path;
    $path['source'] = 'taxonomy/term/' . $term->tid;
    $path['language'] = 'en';
    if (!empty($term->field_taxonomy_term_uri[LANGUAGE_NONE])) {
      $path_alias = str_replace('http://www.informea.org/', '', $term->field_taxonomy_term_uri[LANGUAGE_NONE][0]['url']);
    }
    else {
      $path_alias = 'terms/' . str_replace(' ', '-', trim($term->name));
    }
    $path['alias'] = $path_alias;
    path_save($path);
  }
}

function thesaurus_cronapi() {
  return array(
    'thesaurus_vocbench_export_ontologies' => array(
      'description' => 'Export VocBench ontologies into RDF & Excel',
      'rule' => '*/30 * * * *',
    ),
    'thesaurus_update_path_aliases' => array(
      'description' => 'Update path aliases for Thesaurus terms',
      'rule' => '*/30 * * * *',
    ),
  );
}

function thesaurus_vocbench_export_ontologies() {
  if ($vb_conn = Database::getConnection('default', 'vocbench')) {
    $q = $vb_conn->select('ontology_info', 'a')->fields('a', array());
    $rows = $q->execute()->fetchAll();
    $st = new SemanticTurkey('http://localhost:1979');
    foreach ($rows as $row) {
      $ontology = $row->ontology_name;
      $rdf_filename = SemanticTurkey::slugify($ontology) . '.rdf';
      $rdf_destination = variable_get('thesaurus_rdf_export_dir') . '/' . $rdf_filename;
      if ($st->exportRDF($ontology, $rdf_destination)) {
        // Also generate the Excel file
        $xls_filename = SemanticTurkey::slugify($ontology) . '.xls';
        $xls_destination = variable_get('thesaurus_rdf_export_dir') . '/' . $xls_filename;
        $rdf_url = 'http://www.informea.org/sites/default/files/export/' . $rdf_filename;
        thesaurus_export_to_xls($rdf_url, $xls_destination);
      }
      else {
        watchdog('thesaurus', 'Failed to export ontology ' . $ontology, [], WATCHDOG_ERROR);
      }
    }
    $vb_conn->destroy();
  }
}

function thesaurus_update_path_aliases() {
  Thesaurus::updatePathAliases();
}

/**
 * Implements hook_panels_pane_content_alter().
 */
function thesaurus_panels_pane_content_alter(&$content, $pane, $args, $contexts) {
  $uids = [
    '27524512-75b9-453c-b279-6a96a3a97c21',
    'ac1d8da1-b969-4f4a-9534-e855043e0c74',
    'eccecd17-7675-4501-bb54-dac15e2c7e04',
    '6bd77781-58a1-47ac-99c9-108b15d6e244',
  ];
  if (!empty($pane->uuid) && in_array($pane->uuid, $uids) && empty($content->content['#items'][0]['value'])) {
    // Hide field synonyms on taxonomy term pages if it is empty
    $content = false;
  }
}

function thesaurus_get_tags_in_use($field, $content_type = NULL, $country_id = NULL) {
  $query = db_select("field_data_{$field}", 'a')->fields('a', array("{$field}_tid"));
  if (!empty($content_type)) {
    $query->condition('a.bundle', $content_type);
  }
  if (!empty($country_id)) {
    $query->innerJoin('field_data_field_country', 'b', 'a.entity_id = b.entity_id');
    $query->condition('b.field_country_target_id', $country_id);
  }
  $query->groupBy("{$field}_tid");
  return $query->execute()->fetchCol();
}

/*
 * get term based on synonyms and name
 * */
function thesaurus_get_brs_map_terms($name) {
  static $map = [], $vid;

  if (!$name) {
    return [];
  }

  if (@$map[$name]) {
    return $map[$name];
  }

  if (!$vid) {
    $vdk = taxonomy_vocabulary_machine_name_load('thesaurus_informea');
    $vid = $vdk->vid;
  }

  $tids = [];

  $query = db_select('field_data_field_term_synonyms', 's')
    ->condition('s.field_term_synonyms_value', $name);
  $query->join('taxonomy_term_data', 'td', 'td.tid = s.entity_id');
  $query->fields('td', ['tid', 'name']);
  $all = $query->execute()->fetchAll();
  foreach($all as $row) {
    $tids[$row->tid] = $row->name;
  }
  // No synonyms found
  if (!$tids) {
    $tid = ODataMigrationUtil::getTaxonomyTermByName($name, $vid);
    if ($tid){
      $term = taxonomy_term_load($tid);
      $tids[$tid] = $term->name;
    }
  }

  $map[$name] = $tids;

  return $tids;
}