<?php

/**
 * Implements hook_menu_alter().
 */
function i18n_string_helper_menu_alter(&$items) {
  if (isset($items['admin/config/regional/translate/translate'])) {
    $item = &$items['admin/config/regional/translate/translate'];
    $item['page callback'] = 'i18n_string_helper_locale_translate_seek_screen';
    $item['file'] = 'i18n_string_helper.admin.inc';
    $item['module'] = 'i18n_string_helper';
  }
}

/**
 * Implements hook_form_alter().
 *
 * {@inheritdoc}
 */
function i18n_string_helper_get_strings() {
  $strings = &drupal_static(__FUNCTION__);
  if (!isset($strings)) {
    if ($cache = cache_get('i18n_string_helper_data')) {
      $strings = $cache->data;
    }
    else {
      $strings = module_invoke_all('i18n_string_helper_strings');
      cache_set('i18n_string_helper_data', $strings, 'cache');
    }
  }
  return $strings;
}
